
version: "3"
services:
  redis:
    #container_name: redis
    image: 'docker.io/bitnami/redis:6.2-debian-10'
    environment:
      - REDIS_PASSWORD=laSQL2019
      # - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6002:6379'
    #volumes:
    #  - 'redis_data:/bitnami/redis/data'
    #networks:
    #  - rsq_network

  python-api:
    image: python
    #container_name: python-api
    build:
      context: ./api/
    ports:
      - "5002:5001"
    # expose:
    #   - "5001"
    command: 'python3 api.py'
    #volumes:
    #  - 'python_data:/app'
    #depends_on:
    #  - redis
    #links: 
    #  - redis
    #networks:
    #  - rsq_network

  node-app:
    #container_name: node-app
    restart: unless-stopped
    environment: 
        - NODE_ENV=production
    ports:
      - '3002:3000'
    build:
        context: ./
    #depends_on:
    #  - redis
    #  - python-api
    #links: 
    #  - redis
    #networks:
    #  - rsq_network


#networks:
#  rsq_network:

#volumes:
  #python_data:
  #  driver: local
  #redis_data:
  #  driver: local


